#ggplots

#Grossplots
#plot for the estimated gross per genre 
estimatedGrossPlot <- ggplot(data = coefGrossdf, aes(x=genre, y = calc_gross))  +
  geom_bar(stat="identity", fill="steelblue") + 
  geom_text(aes(label=round(calc_gross,1), vjust= -0.5)) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 12)) +
  ggtitle("Estimated gross per genre calculated by a linear model") +
  scale_y_continuous(labels = unit_format(unit = "M")) +
  labs(x = "Movie genres", y = "Estimated gross in millions")


#plot for the effect of a genre on the gross
effectGrossPlot <- ggplot(data = coefGrossdf, aes(x=genre, y = round(gross/10^6, 2)))  +
  geom_bar(stat="identity", fill="steelblue") + 
  geom_text(aes(label=percentage, vjust= ifelse(percentage > 0, -0.5, 1))) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 12)) +
  ggtitle("Effect of the genre on the expected gross using the intercepts generated by a linear model") +
  labs(x = "Movie genres", y = "Effect on the gross in millions")


#plot for the change in gross per genre over the decades
grossOverDecadesPlot <- ggplot(data = coefGrossDecadesdf, aes(x=decade, y = calc_gross, colour= genre)) +
  geom_line() +
  geom_point() +
  facet_wrap(~genre) +
  labs(x = "Decades", y = "Estimated gross in millions")


#scoreplots
#plot for the estimated score per genre
estimatedScorePlot <- ggplot(data = coefScoredf, aes(x=genre, y = calc_score))  +
  geom_bar(stat="identity", fill="steelblue") + 
  geom_text(aes(label=calc_score, vjust= -0.5)) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 12)) +
  ggtitle("Estimated score per genre calculated by a linear model") +
  labs(x = "Movie genres", y="Estimated score")


#plot for the effect of a genre on the score
effectScorePlot <- ggplot(data = coefScoredf, aes(x=genre, y = round(imdb_score,2)))  +
  geom_bar(stat="identity", fill="steelblue") + 
  geom_text(aes(label=round(imdb_score, 2), vjust= ifelse(imdb_score > 0, -0.5, 1))) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 12)) +
  ggtitle("Effect of the genre on the expected score using the intercepts generated by a linear model") +
  labs(x = "Movie genres", y= "Effect on the score")


#plot for the change in score per genre over the decades
scoreOverDecadesPlot <- ggplot(data = coefScoreDecadesdf, aes(x=decade, y = calc_Score, colour= genre)) +
  geom_line() +
  geom_point() +
  facet_wrap(~genre) +
  labs(x = "Decades", y = "Estimated score")


calcScore  <- function(input) {
  if(length(input ) > 0 ) {
    start <- coefScoreintercept
    for(x in input){
      start <- start + coefScoredf$imdb_score[coefScoredf$genre == x]
    }
    return (round(start,2)) }
  else {
    return (0)
  }
}

calcGross <- function(input) {
  if(length(input) > 0) {
    start = coefGrossintercept
    for(x in input){
      start <- start + coefGrossdf$gross[coefGrossdf$genre == x]
    }
    return (round(start / 10^6, 2)) }
  else {
    return (0)
  }
}